### ISSUE TITLE
GraphQl Handlers break for Iron 0.5.1

### ISSUE THREAD

**Issue by TheServerAsterisk** [mhallin/juniper#21]
The error messages I receive are: 

```
trait `for<'r, 'r, 'r> juniper::iron_handlers::GraphiQLHandler: std::ops::Fn<(&'r mut iron::request::Request<'r, 'r>,)>` not satisfied
```

```
trait `for<'r, 'r, 'r> juniper::iron_handlers::GraphiQLHandler: std::ops::FnOnce<(&'r mut iron::request::Request<'r, 'r>,)>` not satisfied
```

```
trait `for<'r, 'r, 'r> juniper::iron_handlers::GraphQLHandler<'_, _, _, _, _>: std::ops::Fn<(&'r mut iron::request::Request<'r, 'r>,)>` not satisfied
```

```
trait `for<'r, 'r, 'r> juniper::iron_handlers::GraphQLHandler<'_, _, _, _, _>: std::ops::FnOnce<(&'r mut iron::request::Request<'r, 'r>,)>` not satisfied
```

**Comment by zaeleus** [comment]
This error is because of an iron version mismatch between your application (0.5.1) and juniper (0.4.x).

I have a patch to update iron, but it's blocked until iron-test updates to iron 0.5. If you're using your own fork of juniper, you can actually just bump juniper's iron dependency and then ignore the deprecation warnings and don't run the tests. Otherwise, I would suggest staying on iron 0.4.
