### ISSUE TITLE
Mutations

### ISSUE THREAD

**Issue by theduke** [mhallin/juniper#27]
I can't find anything about mutations in the docs.

Are they supported at all?

**Comment by TheServerAsterisk** [comment]
Yup, mutations are supported.  More specifically, the fourth argument of [graphqlhandler::new](mhallin.github.io/juniper/juniper/iron_handlers/struct.GraphQLHandler.html#method.new) allows you to place some struct that implements the graphqltype trait.  From there the struct just needs to implement the fields and logic for your mutations.  Unfortunately,  the [example](https://github.com/mhallin/juniper/blob/90054cf9d1848ddf00245462b3272cd1dc4b815c/examples/server.rs) only shows how to construct a server with no mutations at all. I have the intention to build a complete example, but keep getting sidetracked.

**Comment by theduke** [comment]
I'm in that situation, I intend to use Juniper with `hyper` directly rather than with Iron.

**Comment by TheServerAsterisk** [comment]
Hmmm, I am not 100% familiar with hyper, but I would assume it is fairly analogous when using hypers server. The main difference being that the [GraphQlHandler](https://github.com/mhallin/juniper/blob/master/src/integrations/iron_handlers.rs#L25) would have to implement the Handler trait in hyper which would allow you to use very similar logic if not almost the same logic, the difference being you might have to deal with more hyper related parameters.

**Comment by mhallin** [comment]
Yeah, I realize that mutations are pretty undocumented. The reason for that is primarily because they work pretty much the same way as queries :)

Some libraries make mutations behave different from queries, but Juniper treats them the same because they _are_ basically the same. They are just root fields with another namespace. For example:

```rust
graphql_object!(Query: Ctx |&self| {
    // ... your query object
});

graphql_object!(Mutations: Ctx |&self| {
    field addUser(username: String) -> AddUserResult {
        // ... database logic
        AddUserResult { ok: true }
    }
});
```

As TheServerAsterisk said, you can provide a mutation object when creating the `GraphQLHandler`. If you prefer to work without the Iron integration, you will need to instantiate `RootNode` with the mutation object instead: https://github.com/mhallin/juniper/blob/master/src/schema/model.rs#L63.

I hope this clears things up; let me know if you have any more questions. I'll add improving the documentation to my backlog.

**Comment by theduke** [comment]
Yeah that clears things up, thanks.
