### ISSUE TITLE
Method not allowed for OPTIONS

### ISSUE THREAD

**Issue by drager** [mhallin/juniper#41]
Hi, thank you for this library!

I'm having some trouble using my GraphQL API from an Javascript application since it results in 405 (Method Not Allowed). I saw here that you only allow `GET` and `POST`: https://github.com/mhallin/juniper/blob/master/src/integrations/iron_handlers.rs#L161-L163

How come it's like this and how can I proceed from here?

Thank you!

**Comment by TheServerAsterisk** [comment]
I am assuming you are using iron based upon your link. 

One way to solve this issue is to implement the `AfterMiddleware` trait or a `BeforeMiddleware` trait that can deal with the option verb and add it to the chain. For example (you'll note that I included a very relaxed access control policy as well): 

```rust
struct CorsHandler;

impl AfterMiddleware for CorsHandler {
    fn after(&self, request: &mut Request, mut res: Response) -> IronResult<Response> {
        match request.method {
            Method::Options => {
                let mut headers = Headers::new();
                headers.set(AccessControlAllowOrigin::Any);
                headers.set(AccessControlAllowMethods(vec![Method::Post,
                                                           Method::Get,
                                                           Method::Options]));
                headers.set(AccessControlMaxAge(17280u32));
                headers.set(Accept(vec![qitem(Mime(TopLevel::Application,
                                                   SubLevel::Json,
                                                   vec![]))]));

                headers.set(AccessControlAllowHeaders(vec![UniCase("Content-Type".to_owned())]));
                res.headers = headers;
                res.status = Some(Status::Ok);
                Ok(res)
            }
            Method::Post => {
                res.headers.set(AccessControlAllowOrigin::Any);
                Ok(res)
            }
            Method::Get => {
                res.headers.set(AccessControlAllowOrigin::Any);
                Ok(res)
            }
            _ => Ok(Response::with(Status::InternalServerError)),
        }
    }

    fn catch(&self, _: &mut Request, err: IronError) -> IronResult<Response> {
        info!("{:?}", err);
        Ok(Response::with(Status::InternalServerError))
    }
}
```
While I can't specify the exact reason why since I am not the author, but it would be somewhat "dangerous" to implement the option verb for other individuals since the option verb is usually used in conjunction with access control. 

Also, it doesn't seem the express version doesn't [support](https://github.com/graphql/express-graphql/issues/14) option +  cors headers out of the box, but rather suggests the developer use middleware to catch the option verb and respond appropriately.   

An alternative solution to this is to host the graphql server on the same domain and port as the website/where the js code is being executed which I believe should prevent the need for the option header altogether.

**Comment by mhallin** [comment]
Thanks for the reply, @TheServerAsterisk. Great example.

For some background on the Iron integration: I'm trying to keep the framework integration code as small as possible, mainly for the reason that it's hard to make sweeping assumptions on *which* extra features methods to provide (CORS? CSRF? Authentication?).

So if the integration is kept minimal, it will be easy to write middlewares around it which don't even have to know about Juniper. CORS, CSRF, and authentication are all topics that apply to *all* APIs one would want to write with Iron, so it makes sense that they would live in isolated crates with minimal knowledge of the rest of the system.

**Comment by drager** [comment]
@TheServerAsterisk: Thank you so much for your answer! Really appreciate it.
@mhallin: Thank you! I agree on keeping the integration simple.

Maybe this issue just came up from my novice experience with Iron so thank you guys for the background on the integration and the great example.
