### ISSUE TITLE
Dynamic Schema(s)

### ISSUE THREAD

**Issue by dbettin** [mhallin/juniper#7]
- Are there plans to support the schema language?
- Is it possible to generate a schema dynamically?

**Comment by mhallin** [comment]
Hello!

I haven't given much thought to the schema language. What would be your use case for schema language support? Are there any tools that produce or consume this representation?

What do you mean with "generate a schema dynamically"? All exposed types today must implement the `GraphQLType` trait, which means that a schema is fixed at compilation time.

**Comment by Mange** [comment]
Some people respond with different schemas depending on auth context and whatever. Maybe @dbettin  is referring to that?

**Comment by dbettin** [comment]
We are planning to build graphql schema designers. These schemas could live in a database for example. So they would not be able to be statically defined in code.

**Comment by mhallin** [comment]
I see. Unfortunately, I don't think this library is suited for that use case. In order to do this with Juniper, you would need to bypass all functionality provided by implementing the `GraphQLType` trait. It would be possible to build a meta-model of the schema using the API in https://github.com/mhallin/juniper/blob/master/src/schema/meta.rs, but you would need to implement a custom query executor that only relied on your database model.

To answer @Mange's question, that should be possible by using different `RootNode` instances depending on e.g. auth context.

**Comment by dynaxis** [comment]
@dbettin so could you share me which route you took for your case? I have a similar requirement.
